### ISSUE TITLE
A README

### ISSUE THREAD

**Issue by ghost** [mebens/blackbulletiv.github.com#1]
This is a nice site. It appears that you are using a custom Jekyll.

A README with some info on
- what Jekyll you are using
- what plugins
- any custom stuff outside normal Jekyll

would be big help to people getting started.

**Comment by mebens** [comment]
I think a README would be a good idea; I'll have do get onto that sometime soon. I'm not using a custom Jekyll though, only a bunch of plugins that I've written (included in `_plugins` directory of course). If someone downloads this, they should be able to compile the site with the latest Jekyll (I'm using 0.11.0 at present).

**Comment by mebens** [comment]
Looks like I forgot about this. :P Anyway, I've added a simple README to the site.
